/**
 * lib/clinical/quadEngine/modules/vastusStrain/vastusStrainExercises.mjs
 * ---------------------------------------------------------------------------
 * Exercise library for VL / VM / VI muscle strains. The vastii are
 * MONOARTICULAR (cross only the knee), so loading is knee-extension-biased and
 * there is no hip-flexion/stretch interaction to manage (the key contrast with
 * rectus femoris). Stretch is progressed normally (unlike contusion).
 *
 * Deepened library: ~37 exercises across the 6-phase muscle model, with
 * regressions/progressions, equipment variants, BFR (Hughes 2019) for early
 * low-load hypertrophy, VMO-biased work for medial strains, and criteria-based
 * return-to-sport testing (Nawasreh 2016; Thompson 2022).
 *
 * Inert metadata + beta-default dosage only. dosage_by_tier = [early, mid, late].
 * `muscle_bias` lets the module rank VMO/VL-specific work for the injured head.
 * ---------------------------------------------------------------------------
 */

export const VASTUS_STRAIN_EXERCISES = [
  // ═══ FOUNDATION (calm & protect) ═════════════════════════════════════════
  {
    id: 'VS-EX-001', name: 'Pain-free quad isometric (knee near extension)', block: 'tissue_specific_loading', phase: 'foundation',
    purpose: 'Activate the quadriceps without movement, at a length the strain tolerates.',
    why: 'Isometrics restore neural drive and tolerate load early in muscle healing (Lempainen 2022).',
    contraction: 'isometric', stretch_demand: 'low', knee_position: 'near_extension', muscle_bias: 'all',
    equipment: ['bodyweight'], source_refs: ['QUAD-CIT-001'],
    dosage_by_tier: [{ sets: '3', hold: '10-20 s', intensity: 'pain-free submaximal' }, { sets: '4', hold: '20-30 s' }, { sets: '4-5', hold: '30-45 s' }],
    instructions: ['Sit or lie with the knee almost straight.', 'Tighten the thigh to press the back of the knee down.', 'Hold without pain, breathe, release slowly.'],
    regression: 'reduce hold time / effort', progression: 'VS-EX-002',
    cautions: ['Stay strictly pain-free.'],
  },
  {
    id: 'VS-EX-002', name: 'Inner-range quad (short-arc knee extension)', block: 'tissue_specific_loading', phase: 'foundation',
    purpose: 'Rebuild terminal knee extension with a small, controlled range.',
    why: 'Short-arc terminal extension loads the vasti (esp. VMO) safely in early healing.',
    contraction: 'isotonic_short_arc', stretch_demand: 'low', knee_position: 'terminal_extension', muscle_bias: 'vastus_medialis',
    equipment: ['bodyweight', 'support_optional'], source_refs: ['QUAD-CIT-001'],
    dosage_by_tier: [{ sets: '2-3', reps: '10', range: 'last 20-30 deg' }, { sets: '3', reps: '12-15' }, { sets: '3', reps: '15' }],
    instructions: ['Place a rolled towel under the knee.', 'Straighten the knee the last part of the range.', 'Lower slowly under control.'],
    regression: 'VS-EX-001', progression: 'VS-EX-011',
    cautions: ['Keep within a comfortable range.'],
  },
  {
    id: 'VS-EX-003', name: 'Straight-leg raise', block: 'strength_support', phase: 'foundation',
    purpose: 'Load the quadriceps in a long lever without bending the knee.',
    why: 'Confirms quad integrity and builds early strength; an inability to SLR is a rupture red flag.',
    contraction: 'isometric_dynamic', stretch_demand: 'low', knee_position: 'extension', muscle_bias: 'all',
    equipment: ['bodyweight'], source_refs: ['QUAD-CIT-001', 'QUAD-CIT-013'],
    dosage_by_tier: [{ sets: '2', reps: '8-10' }, { sets: '3', reps: '10' }, { sets: '3', reps: '12-15' }],
    instructions: ['Lie on your back, one knee bent.', 'Keep the injured leg straight and lift to the height of the other thigh.', 'Lower slowly.'],
    regression: 'reduce reps / range', progression: 'add ankle weight',
    cautions: ['Stop if you cannot keep the knee locked straight.'],
  },
  {
    id: 'VS-EX-004', name: 'Quad isometric with BFR cuff (low load)', block: 'tissue_specific_loading', phase: 'foundation',
    purpose: 'Preserve quad muscle size early when heavy loading is not tolerated.',
    why: 'Low-load BFR matched heavy-load training for quad hypertrophy/strength with less pain (Hughes 2019).',
    contraction: 'isometric', stretch_demand: 'low', knee_position: 'mid_range', muscle_bias: 'all',
    equipment: ['bfr_cuff'], source_refs: ['QUAD-CIT-015'], requires_supervision: true,
    dosage_by_tier: [{ sets: '4', reps: '30/15/15/15', intensity: '20-30% effort', cuff: '~80% AOP' }, { sets: '4', reps: '30/15/15/15' }, { sets: '4', reps: '30/15/15/15' }],
    instructions: ['Apply the cuff to the upper thigh under supervision.', 'Perform low-load quad work to the prescribed reps.'],
    regression: 'VS-EX-001 (no cuff)', progression: 'VS-EX-011',
    cautions: ['Supervised application only; not if circulatory contraindications.'],
  },
  {
    id: 'VS-EX-005', name: 'Seated knee extension hold (mid-range)', block: 'tissue_specific_loading', phase: 'foundation',
    purpose: 'Mid-range isometric to bridge toward dynamic loading.',
    why: 'Graded isometric angle progression builds tolerance across the range.',
    contraction: 'isometric', stretch_demand: 'low', knee_position: 'mid_range', muscle_bias: 'all',
    equipment: ['bodyweight', 'band'], source_refs: ['QUAD-CIT-001'],
    dosage_by_tier: [{ sets: '3', hold: '15 s' }, { sets: '3', hold: '25 s' }, { sets: '4', hold: '30 s' }],
    instructions: ['Sit with the knee bent ~45 deg, hold an isometric push into a band or fixed object.'],
    regression: 'VS-EX-001', progression: 'VS-EX-011',
    cautions: [],
  },
  {
    id: 'VS-EX-006', name: 'Stationary cycling (high seat, light)', block: 'conditioning', phase: 'foundation',
    purpose: 'Gentle circulation and pain-free knee movement.',
    why: 'Low-load cycling maintains conditioning without provoking the strain.',
    contraction: 'dynamic', stretch_demand: 'low', knee_position: 'cyclic', muscle_bias: 'all',
    equipment: ['bike'], source_refs: ['QUAD-CIT-002'],
    dosage_by_tier: [{ sets: '—', detail: '5-10 min light' }, { sets: '—', detail: '10-15 min' }, { sets: '—', detail: '15-20 min' }],
    instructions: ['Keep resistance light and cadence comfortable.'],
    regression: 'shorter duration', progression: 'add resistance',
    cautions: ['Stop if pain rises.'],
  },

  // ═══ RELOAD (restore movement & base) ════════════════════════════════════
  {
    id: 'VS-EX-010', name: 'Bodyweight wall sit', block: 'tissue_specific_loading', phase: 'reload',
    purpose: 'Sustained quad loading in a mid-range position.',
    why: 'Mid-range isometric builds capacity before dynamic loading.',
    contraction: 'isometric', stretch_demand: 'low', knee_position: 'mid_range', muscle_bias: 'all',
    equipment: ['wall'], source_refs: ['QUAD-CIT-001'],
    dosage_by_tier: [{ sets: '3', hold: '20-30 s', angle: 'shallow' }, { sets: '3', hold: '30-45 s' }, { sets: '4', hold: '45-60 s', angle: '~90 deg' }],
    instructions: ['Back against a wall, slide to a comfortable depth.', 'Hold with even weight through both legs.'],
    regression: 'shallower depth', progression: 'single-leg emphasis',
    cautions: ['Reduce depth if the front of the thigh complains.'],
  },
  {
    id: 'VS-EX-011', name: 'Full-range knee extension (machine or band)', block: 'tissue_specific_loading', phase: 'reload',
    purpose: 'Concentric/eccentric quad loading through full knee range.',
    why: 'Progressive isotonic loading drives muscle regeneration (Lempainen 2022).',
    contraction: 'isotonic', stretch_demand: 'moderate', knee_position: 'full_range', muscle_bias: 'all',
    equipment: ['band', 'machine_optional'], source_refs: ['QUAD-CIT-001'],
    dosage_by_tier: [{ sets: '3', reps: '12', tempo: 'slow' }, { sets: '3', reps: '10-12' }, { sets: '4', reps: '8-10', load: 'moderate' }],
    instructions: ['Extend the knee fully, then lower slowly over 3 seconds.'],
    regression: 'VS-EX-002', progression: 'VS-EX-022',
    cautions: ['Eccentric (lowering) should stay controlled and pain-free.'],
  },
  {
    id: 'VS-EX-012', name: 'Split squat (supported)', block: 'strength_support', phase: 'reload',
    purpose: 'Single-leg quad-biased strength with support for balance.',
    why: 'Re-introduces functional single-leg loading.',
    contraction: 'isotonic', stretch_demand: 'moderate', knee_position: 'functional', muscle_bias: 'all',
    equipment: ['support_optional'], source_refs: ['QUAD-CIT-001'],
    dosage_by_tier: [{ sets: '2', reps: '8 each' }, { sets: '3', reps: '8-10 each' }, { sets: '3', reps: '10-12 each' }],
    instructions: ['Stagger your stance, lower the back knee toward the floor, drive up.'],
    regression: 'reduce depth / hold rail', progression: 'VS-EX-021',
    cautions: ['Hold a rail for balance as needed.'],
  },
  {
    id: 'VS-EX-013', name: 'Leg press (double-leg, moderate)', block: 'strength_support', phase: 'reload',
    purpose: 'Controlled bilateral quad loading through range.',
    why: 'Closed-chain pressing rebuilds force capacity with low joint stress.',
    contraction: 'isotonic', stretch_demand: 'moderate', knee_position: 'full_range', muscle_bias: 'all',
    equipment: ['machine', 'gym'], source_refs: ['QUAD-CIT-001'],
    dosage_by_tier: [{ sets: '3', reps: '12' }, { sets: '3', reps: '10' }, { sets: '4', reps: '8' }],
    instructions: ['Press through a comfortable range, controlling the lowering phase.'],
    regression: 'reduce range/load', progression: 'single-leg press',
    cautions: [],
  },
  {
    id: 'VS-EX-014', name: 'Spanish squat (band-resisted isometric)', block: 'tissue_specific_loading', phase: 'reload',
    purpose: 'Knee-biased isometric loading that spares hip drive.',
    why: 'Band-resisted wall isometric heavily loads the quad with low movement demand.',
    contraction: 'isometric', stretch_demand: 'low', knee_position: 'mid_range', muscle_bias: 'all',
    equipment: ['band'], source_refs: ['QUAD-CIT-008'],
    dosage_by_tier: [{ sets: '4', hold: '30 s' }, { sets: '5', hold: '30-45 s' }, { sets: '5', hold: '45 s' }],
    instructions: ['Loop a strong band behind the knees to a fixed post, sit back into the band and hold.'],
    regression: 'wall sit', progression: 'add load (vest)',
    cautions: [],
  },
  {
    id: 'VS-EX-015', name: 'VMO-biased terminal knee extension (step / band)', block: 'tissue_specific_loading', phase: 'reload',
    purpose: 'Bias the vastus medialis oblique for medial-head strains.',
    why: 'Terminal-range and weight-bearing extension preferentially recruit VMO (PubMed PMID 26940378).',
    contraction: 'isotonic_short_arc', stretch_demand: 'low', knee_position: 'terminal_extension', muscle_bias: 'vastus_medialis',
    equipment: ['band', 'step'], source_refs: ['QUAD-CIT-001'],
    dosage_by_tier: [{ sets: '3', reps: '12' }, { sets: '3', reps: '15' }, { sets: '4', reps: '15' }],
    instructions: ['Drive the last 20-30 deg of extension against band resistance, emphasising the inner thigh.'],
    regression: 'VS-EX-002', progression: 'VS-EX-021',
    cautions: [],
  },
  {
    id: 'VS-EX-016', name: 'Step-up (low box)', block: 'strength_support', phase: 'reload',
    purpose: 'Functional single-leg quad loading in a familiar pattern.',
    why: 'Step-ups bridge isolated work to closed-chain function.',
    contraction: 'isotonic', stretch_demand: 'moderate', knee_position: 'functional', muscle_bias: 'all',
    equipment: ['step'], source_refs: ['QUAD-CIT-001'],
    dosage_by_tier: [{ sets: '2-3', reps: '8 each', height: 'low' }, { sets: '3', reps: '10 each' }, { sets: '3', reps: '12 each', height: 'higher' }],
    instructions: ['Step up driving through the injured leg, control the step down.'],
    regression: 'lower box', progression: 'add load',
    cautions: [],
  },

  // ═══ ACCUMULATION (build strength & capacity) ════════════════════════════
  {
    id: 'VS-EX-020', name: 'Heavy goblet / front squat', block: 'strength_support', phase: 'accumulation',
    purpose: 'Build maximal quad strength through range.',
    why: 'Heavier loading rebuilds force capacity in the remodeling phase.',
    contraction: 'isotonic', stretch_demand: 'moderate', knee_position: 'full_range', muscle_bias: 'all',
    equipment: ['dumbbell', 'gym'], source_refs: ['QUAD-CIT-001'],
    dosage_by_tier: [{ sets: '3', reps: '8-10' }, { sets: '4', reps: '6-8' }, { sets: '4', reps: '5-6', load: 'heavy' }],
    instructions: ['Squat to a depth you control, keeping even weight through the injured leg.'],
    regression: 'VS-EX-013', progression: 'back squat',
    cautions: ['Build load only while pain-free during and next day.'],
  },
  {
    id: 'VS-EX-021', name: 'Bulgarian split squat', block: 'strength_support', phase: 'accumulation',
    purpose: 'Single-leg strength and control under load.',
    why: 'Closes the strength gap between legs (limb symmetry).',
    contraction: 'isotonic', stretch_demand: 'moderate', knee_position: 'functional', muscle_bias: 'all',
    equipment: ['bench', 'dumbbell'], source_refs: ['QUAD-CIT-001', 'QUAD-CIT-016'],
    dosage_by_tier: [{ sets: '3', reps: '8 each' }, { sets: '3', reps: '8-10 each' }, { sets: '4', reps: '10 each', load: 'added' }],
    instructions: ['Rear foot elevated, lower under control, drive through the front heel.'],
    regression: 'VS-EX-012', progression: 'add load / deficit',
    cautions: [],
  },
  {
    id: 'VS-EX-022', name: 'Eccentric overload knee extension', block: 'tissue_specific_loading', phase: 'accumulation',
    purpose: 'Emphasise the lengthening contraction to build tissue tolerance.',
    why: 'Eccentric loading is a key adaptation stimulus for muscle strains (Lempainen 2022).',
    contraction: 'eccentric', stretch_demand: 'moderate', knee_position: 'full_range', muscle_bias: 'all',
    equipment: ['machine', 'gym'], source_refs: ['QUAD-CIT-001'],
    dosage_by_tier: [{ sets: '3', reps: '8', tempo: '4 s lower' }, { sets: '4', reps: '6-8' }, { sets: '4', reps: '6', load: 'heavy eccentric' }],
    instructions: ['Lift with both legs, lower slowly with the injured leg over 4 seconds.'],
    regression: 'VS-EX-011', progression: 'flywheel eccentric',
    cautions: ['Introduce eccentric overload only when full-range loading is pain-free.'],
  },
  {
    id: 'VS-EX-023', name: 'Single-leg press', block: 'strength_support', phase: 'accumulation',
    purpose: 'Isolated single-leg pressing strength and symmetry.',
    why: 'Quantifiable single-leg loading targets the limb-symmetry deficit.',
    contraction: 'isotonic', stretch_demand: 'moderate', knee_position: 'full_range', muscle_bias: 'all',
    equipment: ['machine', 'gym'], source_refs: ['QUAD-CIT-001', 'QUAD-CIT-016'],
    dosage_by_tier: [{ sets: '3', reps: '10 each' }, { sets: '4', reps: '8 each' }, { sets: '4', reps: '6 each', load: 'heavy' }],
    instructions: ['Press with the injured leg only, matching the uninjured side over time.'],
    regression: 'VS-EX-013', progression: 'add load',
    cautions: [],
  },
  {
    id: 'VS-EX-024', name: 'Flywheel squat (eccentric overload)', block: 'strength_support', phase: 'accumulation',
    purpose: 'Eccentric-biased overload through the squat pattern.',
    why: 'Flywheel devices deliver supramaximal eccentric load shown to aid tendon/muscle capacity.',
    contraction: 'eccentric', stretch_demand: 'moderate', knee_position: 'functional', muscle_bias: 'all',
    equipment: ['flywheel_device', 'gym'], source_refs: ['QUAD-CIT-011'],
    dosage_by_tier: [{ sets: '3', reps: '8' }, { sets: '4', reps: '8' }, { sets: '4', reps: '8', load: 'higher inertia' }],
    instructions: ['Resist the flywheel pull on each eccentric, controlling the deceleration.'],
    regression: 'VS-EX-022', progression: 'higher inertia',
    cautions: [],
  },
  {
    id: 'VS-EX-025', name: 'Walking lunge (loaded)', block: 'strength_support', phase: 'accumulation',
    purpose: 'Dynamic single-leg strength with a forward travel component.',
    why: 'Adds locomotor demand to single-leg strength before running.',
    contraction: 'isotonic', stretch_demand: 'moderate', knee_position: 'functional', muscle_bias: 'all',
    equipment: ['dumbbell'], source_refs: ['QUAD-CIT-001'],
    dosage_by_tier: [{ sets: '2-3', reps: '8 each' }, { sets: '3', reps: '10 each' }, { sets: '3', reps: '12 each', load: 'heavier' }],
    instructions: ['Lunge forward under control, keeping the front knee tracking over the foot.'],
    regression: 'static lunge', progression: 'add load',
    cautions: [],
  },
  {
    id: 'VS-EX-026', name: 'Isokinetic / quantified strength check', block: 'tissue_specific_loading', phase: 'accumulation',
    purpose: 'Measure quad strength symmetry objectively before advancing.',
    why: 'Strength testing must accompany hop testing — hop symmetry can mask quad deficits (Thompson 2022).',
    contraction: 'isokinetic', stretch_demand: 'low', knee_position: 'full_range', muscle_bias: 'all',
    equipment: ['isokinetic_dynamometer', 'gym'], source_refs: ['QUAD-CIT-017', 'QUAD-CIT-016'], is_test: true,
    dosage_by_tier: [{ sets: '—', detail: 'record LSI at 60 and 180 deg/s' }, { sets: '—', detail: 'target >=90% LSI' }, { sets: '—', detail: 'confirm before sprint phase' }],
    instructions: ['Where available, measure injured vs uninjured peak torque; otherwise use single-leg press load symmetry.'],
    cautions: ['A self-reported estimate is screening only.'],
  },

  // ═══ TRANSITION (running & sport prep) ═══════════════════════════════════
  {
    id: 'VS-EX-030', name: 'Linear jogging build-up', block: 'running_sport_prep', phase: 'transition',
    purpose: 'Reintroduce running load progressively.',
    why: 'Graded running exposure precedes high-speed work.',
    contraction: 'dynamic', stretch_demand: 'moderate', speed_power: 'low_to_moderate', muscle_bias: 'all',
    equipment: ['bodyweight'], source_refs: ['QUAD-CIT-001', 'QUAD-CIT-002'],
    dosage_by_tier: [{ sets: '—', detail: '60-70% effort, straight-line' }, { sets: '—', detail: '70-80% effort' }, { sets: '—', detail: '80% with strides' }],
    instructions: ['Build pace over the session; stay pain-free.'],
    regression: 'walk-jog intervals', progression: 'VS-EX-040',
    cautions: ['No sprinting yet.'],
  },
  {
    id: 'VS-EX-031', name: 'Decline/step-down control', block: 'control_balance', phase: 'transition',
    purpose: 'Eccentric quad control under bodyweight in a functional pattern.',
    why: 'Builds deceleration control needed for sport.',
    contraction: 'eccentric', stretch_demand: 'moderate', knee_position: 'functional', muscle_bias: 'all',
    equipment: ['step'], source_refs: ['QUAD-CIT-001'],
    dosage_by_tier: [{ sets: '3', reps: '8 each' }, { sets: '3', reps: '10 each' }, { sets: '3', reps: '12 each', height: 'higher step' }],
    instructions: ['Stand on a step, lower the other foot slowly to tap the floor, return.'],
    regression: 'lower step', progression: 'single-leg squat',
    cautions: [],
  },
  {
    id: 'VS-EX-032', name: 'Double-leg jump & soft landing', block: 'control_balance', phase: 'transition',
    purpose: 'Introduce low-level plyometric loading and landing mechanics.',
    why: 'Landing control precedes reactive single-leg plyometrics.',
    contraction: 'plyometric', stretch_demand: 'moderate', speed_power: 'moderate', muscle_bias: 'all',
    equipment: ['bodyweight'], source_refs: ['QUAD-CIT-001'],
    dosage_by_tier: [{ sets: '3', reps: '6' }, { sets: '3', reps: '8' }, { sets: '4', reps: '8' }],
    instructions: ['Jump and land softly with bent knees, absorbing evenly.'],
    regression: 'jump to step', progression: 'VS-EX-041',
    cautions: ['Land quietly and controlled.'],
  },
  {
    id: 'VS-EX-033', name: 'Single-leg squat (bodyweight)', block: 'control_balance', phase: 'transition',
    purpose: 'Single-leg strength-endurance and control benchmark.',
    why: 'A key functional milestone for limb symmetry.',
    contraction: 'isotonic', stretch_demand: 'moderate', knee_position: 'functional', muscle_bias: 'all',
    equipment: ['bodyweight', 'support_optional'], source_refs: ['QUAD-CIT-001', 'QUAD-CIT-016'],
    dosage_by_tier: [{ sets: '2-3', reps: '6 each', depth: 'partial' }, { sets: '3', reps: '8 each' }, { sets: '3', reps: '10 each', depth: 'deeper' }],
    instructions: ['Squat on one leg to a controlled depth, keeping the knee aligned.'],
    regression: 'box squat', progression: 'add load',
    cautions: [],
  },
  {
    id: 'VS-EX-034', name: 'Submaximal stride-outs', block: 'running_sport_prep', phase: 'transition',
    purpose: 'Bridge jogging to higher-speed running.',
    why: 'Controlled accelerations prepare the quad for sprint loading.',
    contraction: 'dynamic', stretch_demand: 'moderate', speed_power: 'moderate', muscle_bias: 'all',
    equipment: ['bodyweight'], source_refs: ['QUAD-CIT-002'],
    dosage_by_tier: [{ sets: '4', detail: '60-70 m at 70%' }, { sets: '5', detail: '75-80%' }, { sets: '6', detail: '80-85%' }],
    instructions: ['Accelerate smoothly to the target effort, decelerate gradually.'],
    regression: 'shorter / slower', progression: 'VS-EX-040',
    cautions: [],
  },
  {
    id: 'VS-EX-035', name: 'Multidirectional movement prep (low intensity)', block: 'running_sport_prep', phase: 'transition',
    purpose: 'Introduce gentle change-of-direction loading.',
    why: 'Prepares tissue for cutting before high-speed simulation.',
    contraction: 'dynamic', stretch_demand: 'moderate', speed_power: 'moderate', muscle_bias: 'all',
    equipment: ['bodyweight', 'cones'], source_refs: ['QUAD-CIT-002'],
    dosage_by_tier: [{ sets: '—', detail: 'rounded changes of direction' }, { sets: '—', detail: 'sharper angles' }, { sets: '—', detail: 'planned cutting' }],
    instructions: ['Run easy patterns with gradual direction changes, building sharpness.'],
    regression: 'wider arcs', progression: 'VS-EX-042',
    cautions: [],
  },

  // ═══ SIMULATION (higher-demand exposure) ═════════════════════════════════
  {
    id: 'VS-EX-040', name: 'Accelerated running build-up', block: 'running_sport_prep', phase: 'simulation',
    purpose: 'Expose the quad to high-speed running demands.',
    why: 'Sprint loading is the highest eccentric demand on the quad before return.',
    contraction: 'dynamic', stretch_demand: 'high', speed_power: 'high', muscle_bias: 'all',
    equipment: ['bodyweight'], source_refs: ['QUAD-CIT-001', 'QUAD-CIT-002'],
    dosage_by_tier: [{ sets: '—', detail: 'accelerations 80-90%' }, { sets: '—', detail: 'near-max sprints' }, { sets: '—', detail: 'max sprint volume' }],
    instructions: ['Progress effort across sessions, keeping mechanics clean.'],
    regression: 'VS-EX-034', progression: 'VS-EX-042',
    cautions: ['Only after pain-free strength and jogging.'],
  },
  {
    id: 'VS-EX-041', name: 'Single-leg plyometric progression', block: 'control_balance', phase: 'simulation',
    purpose: 'Reactive strength and single-leg landing control.',
    why: 'Restores stretch-shortening capacity of the quad.',
    contraction: 'plyometric', stretch_demand: 'high', speed_power: 'high', muscle_bias: 'all',
    equipment: ['bodyweight'], source_refs: ['QUAD-CIT-001'],
    dosage_by_tier: [{ sets: '3', reps: '6 single-leg' }, { sets: '3', reps: '8 reactive' }, { sets: '4', reps: '8 bounding' }],
    instructions: ['Progress hops to bounds, focusing on soft, controlled landings.'],
    regression: 'VS-EX-032', progression: 'depth jumps',
    cautions: [],
  },
  {
    id: 'VS-EX-042', name: 'Change-of-direction & cutting drills', block: 'running_sport_prep', phase: 'simulation',
    purpose: 'High-intensity cutting and deceleration exposure.',
    why: 'Cutting loads the quad eccentrically at speed — a common re-injury scenario.',
    contraction: 'dynamic', stretch_demand: 'high', speed_power: 'high', muscle_bias: 'all',
    equipment: ['bodyweight', 'cones'], source_refs: ['QUAD-CIT-002'],
    dosage_by_tier: [{ sets: '—', detail: 'planned 45-deg cuts' }, { sets: '—', detail: 'sharper / faster cuts' }, { sets: '—', detail: 'reactive cutting' }],
    instructions: ['Progress from planned to reactive change-of-direction.'],
    regression: 'VS-EX-035', progression: 'reactive game drills',
    cautions: [],
  },
  {
    id: 'VS-EX-043', name: 'Sport-specific skill loading', block: 'running_sport_prep', phase: 'simulation',
    purpose: 'Integrate the quad into sport movements (kick/jump/sprint as relevant).',
    why: 'Skill-specific exposure precedes full training.',
    contraction: 'dynamic', stretch_demand: 'high', speed_power: 'high', muscle_bias: 'all',
    equipment: ['bodyweight'], source_refs: ['QUAD-CIT-001', 'QUAD-CIT-002'],
    dosage_by_tier: [{ sets: '—', detail: 'controlled skill reps' }, { sets: '—', detail: 'rising volume/intensity' }, { sets: '—', detail: 'near-match intensity' }],
    instructions: ['Build sport-specific skill volume to near-match demands.'],
    regression: 'reduce intensity', progression: 'VS-EX-050',
    cautions: [],
  },
  {
    id: 'VS-EX-044', name: 'Return-to-sport criteria battery', block: 'control_balance', phase: 'simulation',
    purpose: 'Objective gate before full return: strength + hop symmetry + confidence.',
    why: 'Passing a criteria battery (>=90% LSI strength + 4 hop tests) predicts better outcomes (Nawasreh 2016); use strength AND hop tests (Thompson 2022).',
    contraction: 'test', stretch_demand: 'moderate', speed_power: 'high', muscle_bias: 'all',
    equipment: ['bodyweight'], source_refs: ['QUAD-CIT-016', 'QUAD-CIT-017'], is_test: true,
    dosage_by_tier: [{ sets: '—', detail: 'single + triple + crossover + 6 m timed hop LSI' }, { sets: '—', detail: 'quad strength LSI' }, { sets: '—', detail: 'all >=90% + pain-free + confident' }],
    instructions: ['Compare injured vs uninjured on hop tests AND quad strength; target >=90% on all.'],
    cautions: ['Do not clear on hop symmetry alone — confirm strength too.'],
  },

  // ═══ RESILIENCE (return to performance) ══════════════════════════════════
  {
    id: 'VS-EX-050', name: 'Full sport-specific integration', block: 'running_sport_prep', phase: 'resilience',
    purpose: 'Full training load and sport-specific patterns.',
    why: 'Final return-to-performance exposure.',
    contraction: 'dynamic', stretch_demand: 'high', speed_power: 'high', muscle_bias: 'all',
    equipment: ['bodyweight'], source_refs: ['QUAD-CIT-001', 'QUAD-CIT-002'],
    dosage_by_tier: [{ sets: '—', detail: 'modified team training' }, { sets: '—', detail: 'full training' }, { sets: '—', detail: 'match exposure' }],
    instructions: ['Integrate into normal training once all criteria are met.'],
    regression: 'partial training', progression: 'full competition',
    cautions: ['Requires strength symmetry and pain-free sport movements.'],
  },
  {
    id: 'VS-EX-051', name: 'Maintenance strength + eccentric', block: 'strength_support', phase: 'resilience',
    purpose: 'Maintain strength and tissue tolerance to prevent recurrence.',
    why: 'Ongoing eccentric/strength work reduces re-injury risk (~17% recurrence in anterior thigh).',
    contraction: 'mixed', stretch_demand: 'moderate', knee_position: 'full_range', muscle_bias: 'all',
    equipment: ['gym'], source_refs: ['QUAD-CIT-001'],
    dosage_by_tier: [{ sets: '3', reps: '6-8' }, { sets: '3-4', reps: '6' }, { sets: '4', reps: '5-6', load: 'heavy' }],
    instructions: ['Keep 1-2 quad strength sessions per week ongoing.'],
    regression: 'reduce load', progression: 'periodised strength',
    cautions: [],
  },
  {
    id: 'VS-EX-052', name: 'High-speed running maintenance', block: 'running_sport_prep', phase: 'resilience',
    purpose: 'Maintain sprint exposure to keep eccentric tolerance high.',
    why: 'Regular high-speed running is protective against recurrence.',
    contraction: 'dynamic', stretch_demand: 'high', speed_power: 'high', muscle_bias: 'all',
    equipment: ['bodyweight'], source_refs: ['QUAD-CIT-002'],
    dosage_by_tier: [{ sets: '—', detail: 'weekly sprint exposure' }, { sets: '—', detail: 'maintain volume' }, { sets: '—', detail: 'periodise with season' }],
    instructions: ['Keep regular high-speed running in the weekly plan.'],
    regression: 'reduce volume', progression: 'sprint performance work',
    cautions: [],
  },
  {
    id: 'VS-EX-053', name: 'Reactive plyometric maintenance', block: 'control_balance', phase: 'resilience',
    purpose: 'Maintain reactive strength and landing quality.',
    why: 'Sustained plyometric capacity supports performance and resilience.',
    contraction: 'plyometric', stretch_demand: 'high', speed_power: 'high', muscle_bias: 'all',
    equipment: ['bodyweight'], source_refs: ['QUAD-CIT-001'],
    dosage_by_tier: [{ sets: '3', reps: '8' }, { sets: '3-4', reps: '8' }, { sets: '4', reps: '8 varied' }],
    instructions: ['Maintain varied hop/bound work weekly.'],
    regression: 'reduce volume', progression: 'sport-specific plyo',
    cautions: [],
  },
  {
    id: 'VS-EX-054', name: 'Periodised eccentric strength block', block: 'strength_support', phase: 'resilience',
    purpose: 'Keep eccentric tissue tolerance high across a competitive season.',
    why: 'Regular eccentric loading is protective against hamstring/quad strain recurrence when periodised with training load.',
    contraction: 'eccentric', stretch_demand: 'moderate', knee_position: 'full_range', muscle_bias: 'all',
    equipment: ['gym'], source_refs: ['QUAD-CIT-001'],
    dosage_by_tier: [{ sets: '3', reps: '6-8' }, { sets: '3-4', reps: '6' }, { sets: '4', reps: '5-6', load: 'heavy' }],
    instructions: ['Keep a weekly eccentric-emphasis session, adjusting load with competition schedule.'],
    regression: 'VS-EX-022', progression: 'competition taper as needed',
    cautions: [],
  },
  {
    id: 'VS-EX-055', name: 'Movement-quality screen & top-up mobility', block: 'control_balance', phase: 'resilience',
    purpose: 'Monitor for compensations and keep hip/knee mobility from limiting quality movement.',
    why: 'Ongoing movement screening catches early compensations before they become re-injury risk factors.',
    contraction: 'mixed', stretch_demand: 'moderate', knee_position: 'functional', muscle_bias: 'all',
    equipment: ['bodyweight'], source_refs: ['QUAD-CIT-001'],
    dosage_by_tier: [{ sets: '—', detail: 'monthly movement screen + light mobility top-up' }, { sets: '—', detail: 'as needed' }, { sets: '—', detail: 'as needed' }],
    instructions: ['Periodically check squat/lunge/hop quality and address any emerging asymmetry early.'],
    regression: 'none', progression: 'none',
    cautions: [],
  },
];

/** Pool for a given muscle phase. */
export function vastusStrainPool(phaseId) {
  return VASTUS_STRAIN_EXERCISES.filter((e) => e.phase === phaseId);
}
