/**
 * lib/clinical/calfEngine/modules/calfStrain/calfStrainExercises.mjs
 * ---------------------------------------------------------------------------
 * Exercise library for gastrocnemius/soleus (calf) muscle strains.
 * 4-stage functional model: protect -> restore_movement -> build_strength ->
 * return_to_sport. dosage_by_tier = [early, mid, late]. All beta_default.
 * ---------------------------------------------------------------------------
 */

export const CALF_STRAIN_EXERCISES = [
  // ═══ protect ═══════════════════════════════════════════════════════════
  {
    id: 'CF-EX-001', name: 'Pain-free ankle pumps (seated)', block: 'mobility_activation', phase: 'protect',
    purpose: 'Gentle movement and circulation without stressing the calf.',
    why: 'Early gentle movement supports circulation without loading the healing muscle fibres.',
    equipment: ['bodyweight'], source_refs: ['CALF-CIT-001'],
    dosage_by_tier: [{ sets: '3-4', detail: 'pain-free ankle pumps, 10-12 each' }, { sets: '4', detail: '12-15' }, { sets: '4', detail: '15-20' }],
    instructions: ['Sit with the leg supported, gently point and flex the foot within a pain-free range.'],
    regression: 'smaller range', progression: 'CF-EX-010',
    cautions: ['Stay strictly pain-free.'],
  },
  {
    id: 'CF-EX-002', name: 'Protected weight-bearing (heel-raise wedge / support as needed)', block: 'control_balance', phase: 'protect',
    purpose: 'Restore safe walking without stretching the injured calf.',
    why: 'A slight heel lift and shortened stride reduce calf strain during early walking.',
    equipment: ['bodyweight'], source_refs: ['CALF-CIT-001'],
    dosage_by_tier: [{ sets: '—', detail: 'walk with a shorter stride, support/heel lift if it helps' }, { sets: '—', detail: 'increase distance as tolerated' }, { sets: '—', detail: 'walking without a limp' }],
    instructions: ['Take shorter steps and avoid pushing hard off the injured leg.'],
    regression: 'crutches/partial weight-bear', progression: 'CF-EX-011',
    cautions: ['See a clinician if you cannot bear any weight at all.'],
  },
  {
    id: 'CF-EX-003', name: 'Isometric calf activation (mid-range)', block: 'tissue_specific_loading', phase: 'protect',
    purpose: 'Gentle muscle activation without moving through range.',
    why: 'Isometric activation maintains neural drive without stressing the healing muscle through range.',
    equipment: ['bodyweight'], source_refs: ['CALF-CIT-001'],
    dosage_by_tier: [{ sets: '3', hold: '10 s', intensity: 'gentle' }, { sets: '3', hold: '15-20 s' }, { sets: '4', hold: '20-30 s' }],
    instructions: ['Gently push the ball of the foot into the floor without moving the ankle, hold, release.'],
    regression: 'lower effort', progression: 'CF-EX-012',
    cautions: ['Keep effort pain-free.'],
  },
  {
    id: 'CF-EX-004', name: 'Elevation + gentle compression routine', block: 'conditioning', phase: 'protect',
    purpose: 'Support swelling/bruising reduction between active sessions.',
    why: 'Elevation and gentle compression assist early swelling control, especially for higher-grade strains.',
    equipment: ['bodyweight'], source_refs: ['CALF-CIT-006'],
    dosage_by_tier: [{ sets: '—', detail: 'elevate above heart level for 15-20 min, several times daily' }, { sets: '—', detail: 'as needed' }, { sets: '—', detail: 'as needed' }],
    instructions: ['Rest with the leg elevated between activity, especially in the first few days.'],
    regression: 'more frequent rest', progression: 'less needed as swelling settles',
    cautions: [],
  },
  {
    id: 'CF-EX-005', name: 'Pain-free toe curls / intrinsic foot activation', block: 'strength_support', phase: 'protect',
    purpose: 'Keep the lower-leg chain active without loading the calf belly.',
    why: 'Distal foot activation supports circulation and maintains general lower-leg activity.',
    equipment: ['towel'], source_refs: ['CALF-CIT-001'],
    dosage_by_tier: [{ sets: '2-3', reps: '10' }, { sets: '3', reps: '12-15' }, { sets: '3', reps: '15' }],
    instructions: ['Scrunch a towel toward you using only your toes.'],
    regression: 'fewer reps', progression: 'CF-EX-013',
    cautions: [],
  },

  // ═══ restore_movement ══════════════════════════════════════════════════
  {
    id: 'CF-EX-010', name: 'Gentle progressive calf stretch (pain-free range)', block: 'mobility_activation', phase: 'restore_movement',
    purpose: 'Restore comfortable range without provoking the healing muscle.',
    why: 'Gradual, pain-free stretch restores range as the acute phase settles.',
    equipment: ['wall'], source_refs: ['CALF-CIT-001'],
    dosage_by_tier: [{ sets: '2', hold: '15-20 s, gentle' }, { sets: '3', hold: '20-30 s' }, { sets: '3', hold: '30 s' }],
    instructions: ['Lean into a wall with the injured leg straight behind you, stop at a mild, pain-free stretch.'],
    regression: 'CF-EX-001', progression: 'CF-EX-020',
    cautions: ['Stop well short of any pulling pain.'],
  },
  {
    id: 'CF-EX-011', name: 'Double-leg calf raise (partial range)', block: 'tissue_specific_loading', phase: 'restore_movement',
    purpose: 'Rebuild calf strength in a controlled, partial range.',
    why: 'Progressive isotonic loading drives muscle regeneration once the acute phase has settled.',
    equipment: ['bodyweight'], source_refs: ['CALF-CIT-001', 'CALF-CIT-006'],
    dosage_by_tier: [{ sets: '2-3', reps: '10-12', range: 'partial' }, { sets: '3', reps: '15' }, { sets: '3', reps: '15-20', range: 'fuller' }],
    instructions: ['Rise onto the toes with both feet, lower slowly, keep the range comfortable.'],
    regression: 'CF-EX-003', progression: 'CF-EX-021',
    cautions: ['Eccentric (lowering) should stay controlled and pain-free.'],
  },
  {
    id: 'CF-EX-012', name: 'Resisted band ankle plantarflexion', block: 'tissue_specific_loading', phase: 'restore_movement',
    purpose: 'Isolated calf loading without full weight-bearing demand.',
    why: 'Open-chain resisted loading builds capacity while keeping load easily gradeable.',
    equipment: ['band'], source_refs: ['CALF-CIT-001'],
    dosage_by_tier: [{ sets: '2-3', reps: '10-12' }, { sets: '3', reps: '15' }, { sets: '3', reps: '15', load: 'stronger band' }],
    instructions: ['Loop a band around the foot, point the toes against resistance, return slowly.'],
    regression: 'CF-EX-003', progression: 'CF-EX-011',
    cautions: [],
  },
  {
    id: 'CF-EX-013', name: 'Stationary cycling (light)', block: 'conditioning', phase: 'restore_movement',
    purpose: 'Maintain conditioning without impact.',
    why: 'Non-impact conditioning keeps fitness up while the muscle continues healing.',
    equipment: ['bike'], source_refs: ['CALF-CIT-001'],
    dosage_by_tier: [{ sets: '—', detail: '5-10 min light' }, { sets: '—', detail: '10-15 min' }, { sets: '—', detail: '15-20 min' }],
    instructions: ['Keep resistance light and pain-free.'],
    regression: 'shorter duration', progression: 'add resistance',
    cautions: [],
  },
  {
    id: 'CF-EX-014', name: 'Double-leg balance (firm surface)', block: 'control_balance', phase: 'restore_movement',
    purpose: 'Begin re-establishing calf/ankle proprioception.',
    why: 'Balance work re-establishes control before higher loads are introduced.',
    equipment: ['bodyweight'], source_refs: ['CALF-CIT-001'],
    dosage_by_tier: [{ sets: '3', hold: '20-30 s' }, { sets: '3', hold: '30-45 s' }, { sets: '4', hold: '45 s' }],
    instructions: ['Stand on both feet, even weight distribution.'],
    regression: 'hold support', progression: 'CF-EX-024',
    cautions: [],
  },

  // ═══ build_strength ════════════════════════════════════════════════════
  {
    id: 'CF-EX-020', name: 'Full-range calf stretch', block: 'mobility_activation', phase: 'build_strength',
    purpose: 'Complete the range-of-motion picture before higher loads.',
    why: 'Full comfortable range should return before heavier eccentric/plyometric loading.',
    equipment: ['wall', 'step'], source_refs: ['CALF-CIT-001'],
    dosage_by_tier: [{ sets: '2-3', hold: '20-30 s' }, { sets: '3', hold: '30 s' }, { sets: '3', hold: '30-45 s' }],
    instructions: ['Stretch over a step edge or against a wall to a comfortable end-range.'],
    regression: 'CF-EX-010', progression: 'maintain ongoing',
    cautions: [],
  },
  {
    id: 'CF-EX-021', name: 'Single-leg calf raise', block: 'tissue_specific_loading', phase: 'build_strength',
    purpose: 'Build single-leg push-off strength and symmetry.',
    why: 'Closing the single-leg calf strength gap is needed before running/jumping loads.',
    equipment: ['bodyweight'], source_refs: ['CALF-CIT-001', 'CALF-CIT-006'],
    dosage_by_tier: [{ sets: '2-3', reps: '8-10' }, { sets: '3', reps: '12' }, { sets: '3', reps: '15', load: 'add weight' }],
    instructions: ['Rise onto the toes on the injured leg only, lower slowly.'],
    regression: 'CF-EX-011', progression: 'CF-EX-030',
    cautions: [],
  },
  {
    id: 'CF-EX-022', name: 'Seated calf raise (soleus-biased)', block: 'strength_support', phase: 'build_strength',
    purpose: 'Target the soleus specifically with a bent-knee position.',
    why: 'Bent-knee loading biases the soleus, complementing the straight-knee gastrocnemius emphasis of standing raises.',
    equipment: ['bodyweight', 'bench'], source_refs: ['CALF-CIT-001'],
    dosage_by_tier: [{ sets: '2-3', reps: '10-12' }, { sets: '3', reps: '15' }, { sets: '3', reps: '15', load: 'add weight' }],
    instructions: ['Sit with knees bent ~90 degrees, rise onto the toes, lower slowly.'],
    regression: 'CF-EX-011', progression: 'add load',
    cautions: [],
  },
  {
    id: 'CF-EX-023', name: 'Eccentric-emphasis calf lowering', block: 'tissue_specific_loading', phase: 'build_strength',
    purpose: 'Emphasise the lengthening contraction to build tissue tolerance.',
    why: 'Eccentric loading is a key adaptation stimulus for muscle strain recovery.',
    equipment: ['step'], source_refs: ['CALF-CIT-001', 'CALF-CIT-002'],
    dosage_by_tier: [{ sets: '3', reps: '8', tempo: '4 s lower' }, { sets: '3', reps: '10' }, { sets: '4', reps: '10', load: 'added' }],
    instructions: ['Rise with both feet, shift to the injured leg, lower slowly over 3-4 seconds.'],
    regression: 'CF-EX-021', progression: 'CF-EX-031',
    cautions: [],
  },
  {
    id: 'CF-EX-024', name: 'Single-leg balance (unstable surface)', block: 'control_balance', phase: 'build_strength',
    purpose: 'Progress proprioception toward sport demands.',
    why: 'Single-leg balance progression builds capacity for cutting and running.',
    equipment: ['bodyweight', 'balance_pad'], source_refs: ['CALF-CIT-001'],
    dosage_by_tier: [{ sets: '3', hold: '20-30 s' }, { sets: '3', hold: '30-45 s, add pad' }, { sets: '4', hold: '45 s' }],
    instructions: ['Stand on the injured leg only, progress to an unstable surface as it gets easy.'],
    regression: 'CF-EX-014', progression: 'CF-EX-032',
    cautions: [],
  },

  // ═══ return_to_sport ═══════════════════════════════════════════════════
  {
    id: 'CF-EX-030', name: 'Jogging build-up (straight line)', block: 'running_sport_prep', phase: 'return_to_sport',
    purpose: 'Reintroduce running load progressively.',
    why: 'Graded running exposure precedes sprinting and cutting.',
    equipment: ['bodyweight'], source_refs: ['CALF-CIT-006'],
    dosage_by_tier: [{ sets: '—', detail: '60-70% effort, straight-line' }, { sets: '—', detail: '70-80% effort' }, { sets: '—', detail: '80% with strides' }],
    instructions: ['Build pace over the session, stay pain-free.'],
    regression: 'walk-jog intervals', progression: 'CF-EX-031',
    cautions: [],
  },
  {
    id: 'CF-EX-031', name: 'Accelerated sprint build-up', block: 'running_sport_prep', phase: 'return_to_sport',
    purpose: 'Expose the calf to high-speed running demands.',
    why: 'Sprinting is the highest eccentric demand on the calf before return to sport.',
    equipment: ['bodyweight'], source_refs: ['CALF-CIT-001', 'CALF-CIT-006'],
    dosage_by_tier: [{ sets: '—', detail: 'accelerations 80-90%' }, { sets: '—', detail: 'near-max sprints' }, { sets: '—', detail: 'max sprint volume' }],
    instructions: ['Progress effort across sessions, keeping mechanics clean.'],
    regression: 'CF-EX-030', progression: 'CF-EX-033',
    cautions: ['Only after pain-free strength and jogging.'],
  },
  {
    id: 'CF-EX-032', name: 'Single-leg hop and plyometric progression', block: 'control_balance', phase: 'return_to_sport',
    purpose: 'Reactive strength and elastic capacity before sport.',
    why: 'Restores stretch-shortening capacity of the calf-Achilles complex before return.',
    equipment: ['bodyweight'], source_refs: ['CALF-CIT-001'],
    dosage_by_tier: [{ sets: '3', reps: '6 single-leg' }, { sets: '3', reps: '8 reactive' }, { sets: '4', reps: '8 bounding' }],
    instructions: ['Progress hops to bounds, focusing on soft, controlled landings.'],
    regression: 'CF-EX-024', progression: 'depth jumps',
    cautions: [],
  },
  {
    id: 'CF-EX-033', name: 'Change-of-direction / cutting drills', block: 'running_sport_prep', phase: 'return_to_sport',
    purpose: 'Sport-specific cutting and deceleration exposure.',
    why: 'Cutting loads the calf eccentrically at speed — a common re-injury scenario.',
    equipment: ['bodyweight', 'cones'], source_refs: ['CALF-CIT-006'],
    dosage_by_tier: [{ sets: '—', detail: 'planned 45-deg cuts' }, { sets: '—', detail: 'sharper / faster cuts' }, { sets: '—', detail: 'reactive cutting' }],
    instructions: ['Progress from planned to reactive change-of-direction.'],
    regression: 'CF-EX-030', progression: 'reactive game drills',
    cautions: [],
  },
  {
    id: 'CF-EX-034', name: 'Return-to-sport criteria battery', block: 'control_balance', phase: 'return_to_sport',
    purpose: 'Objective gate before full return: strength + hop symmetry.',
    why: 'Criteria-based return (strength + hop symmetry) reduces re-injury risk (Green 2025).',
    equipment: ['bodyweight'], source_refs: ['CALF-CIT-006'], is_test: true,
    dosage_by_tier: [{ sets: '—', detail: 'single + repeated hop LSI' }, { sets: '—', detail: 'calf-raise strength/endurance LSI' }, { sets: '—', detail: 'all >=90% + pain-free sprinting' }],
    instructions: ['Compare injured vs uninjured on hop tests and calf-raise strength/endurance; target >=90% on all.'],
    cautions: ['Do not clear on straight-line running alone — confirm sprint and cutting are pain-free too.'],
  },
];

/** Pool for a given stage. */
export function calfStrainPool(stageId) {
  return CALF_STRAIN_EXERCISES.filter((e) => e.phase === stageId);
}
