/**
 * lib/clinical/ankleEngine/modules/lateralSprain/lateralSprainExercises.mjs
 * ---------------------------------------------------------------------------
 * Exercise library for acute LATERAL ankle ligament sprains (ATFL/CFL,
 * inversion mechanism). Functional/exercise-based rehab is first-line at
 * every grade, including grade III (Kerkhoffs 2007 Cochrane; Vuurberg 2018).
 *
 * 4-stage functional model: protect -> restore_motion -> strength_balance ->
 * return_to_sport. dosage_by_tier = [early, mid, late]. All beta_default.
 * ---------------------------------------------------------------------------
 */

export const LATERAL_SPRAIN_EXERCISES = [
  // ═══ protect: settle pain/swelling, gentle pain-free movement ════════════
  {
    id: 'AS-EX-001', name: 'Ankle pumps / circles (pain-free)', block: 'mobility_activation', phase: 'protect',
    purpose: 'Maintain circulation and gentle range without stressing the healing ligament.',
    why: 'Early gentle movement supports swelling reduction without loading the sprained ligament (Vuurberg 2018).',
    equipment: ['bodyweight'], source_refs: ['ANKLE-CIT-002'],
    dosage_by_tier: [{ sets: '3-4', detail: 'pain-free ankle pumps + circles, 10 each direction' }, { sets: '4', detail: '12-15 each direction' }, { sets: '4', detail: '15-20 each direction' }],
    instructions: ['Move the ankle up/down and in gentle circles within a pain-free range.', 'Stop if it provokes sharp pain.'],
    regression: 'smaller range', progression: 'AS-EX-010',
    cautions: ['Stay strictly pain-free.'],
  },
  {
    id: 'AS-EX-002', name: 'Protected weight-bearing (brace/tape, as tolerated)', block: 'control_balance', phase: 'protect',
    purpose: 'Restore safe walking as early as pain allows.',
    why: 'Early protected weight-bearing (vs prolonged immobilisation) supports functional recovery (Vuurberg 2018).',
    equipment: ['brace_or_tape'], source_refs: ['ANKLE-CIT-002'],
    dosage_by_tier: [{ sets: '—', detail: 'weight-bear as pain allows, brace/tape/support as needed' }, { sets: '—', detail: 'increase walking distance as tolerated' }, { sets: '—', detail: 'walking without a limp' }],
    instructions: ['Use a brace, tape, or supportive shoe if it helps you walk more normally.', 'Avoid limping — reduce distance if you cannot walk without one.'],
    regression: 'crutches/partial weight-bear', progression: 'AS-EX-011',
    cautions: ['See a clinician if you cannot bear any weight at all.'],
  },
  {
    id: 'AS-EX-003', name: 'Isometric ankle activation (all directions)', block: 'tissue_specific_loading', phase: 'protect',
    purpose: 'Gentle muscle activation around the ankle without moving the joint.',
    why: 'Isometric activation maintains neuromuscular drive early without stressing the ligament through range.',
    equipment: ['bodyweight'], source_refs: ['ANKLE-CIT-002'],
    dosage_by_tier: [{ sets: '3', hold: '10 s each direction', intensity: 'gentle' }, { sets: '3', hold: '15-20 s' }, { sets: '4', hold: '20-30 s' }],
    instructions: ['Push the foot gently into a wall/floor in each direction (up, down, in, out) without moving it.'],
    regression: 'lower effort', progression: 'AS-EX-012',
    cautions: ['Keep effort pain-free.'],
  },
  {
    id: 'AS-EX-004', name: 'Seated towel scrunches / toe curls', block: 'strength_support', phase: 'protect',
    purpose: 'Activate the intrinsic foot muscles that support the ankle.',
    why: 'Foot-intrinsic activation supports the arch and ankle stability early.',
    equipment: ['towel'], source_refs: ['ANKLE-CIT-007'],
    dosage_by_tier: [{ sets: '2-3', reps: '10' }, { sets: '3', reps: '12-15' }, { sets: '3', reps: '15' }],
    instructions: ['Scrunch a towel toward you using only your toes.'],
    regression: 'fewer reps', progression: 'AS-EX-013',
    cautions: [],
  },
  {
    id: 'AS-EX-005', name: 'Elevation + gentle compression routine', block: 'conditioning', phase: 'protect',
    purpose: 'Support swelling reduction between active sessions.',
    why: 'Elevation and gentle compression assist early swelling control alongside protected loading.',
    equipment: ['bodyweight'], source_refs: ['ANKLE-CIT-002'],
    dosage_by_tier: [{ sets: '—', detail: 'elevate above heart level for 15-20 min, several times daily' }, { sets: '—', detail: 'as needed' }, { sets: '—', detail: 'as needed' }],
    instructions: ['Rest with the ankle elevated between activity, especially in the first few days.'],
    regression: 'more frequent rest', progression: 'less needed as swelling settles',
    cautions: [],
  },

  // ═══ restore_motion: rebuild ROM + light strength ═════════════════════════
  {
    id: 'AS-EX-010', name: 'Alphabet/ankle-circle full-range drill', block: 'mobility_activation', phase: 'restore_motion',
    purpose: 'Restore full pain-free range of motion.',
    why: 'Progressive active ROM work restores mobility once the acute phase settles.',
    equipment: ['bodyweight'], source_refs: ['ANKLE-CIT-002'],
    dosage_by_tier: [{ sets: '2-3', detail: '"draw the alphabet" with the foot, once through' }, { sets: '3', detail: 'twice through' }, { sets: '3', detail: 'three times through' }],
    instructions: ['Trace the alphabet in the air with your big toe, moving only the ankle.'],
    regression: 'AS-EX-001', progression: 'AS-EX-020',
    cautions: [],
  },
  {
    id: 'AS-EX-011', name: 'Resisted band work (4-way: dorsiflexion/plantarflexion/inversion/eversion)', block: 'tissue_specific_loading', phase: 'restore_motion',
    purpose: 'Rebuild strength through the full range in all directions.',
    why: 'Progressive resisted loading in all planes rebuilds the muscles that dynamically support the ligament.',
    equipment: ['band'], source_refs: ['ANKLE-CIT-002'],
    dosage_by_tier: [{ sets: '2-3', reps: '10 each direction' }, { sets: '3', reps: '12-15 each' }, { sets: '3', reps: '15 each', load: 'stronger band' }],
    instructions: ['Loop a band around the foot and push against it in each of the 4 directions.'],
    regression: 'AS-EX-003', progression: 'AS-EX-021',
    cautions: ['Avoid pushing hard into inversion (rolling inward) early — that direction reproduces the sprain mechanism.'],
  },
  {
    id: 'AS-EX-012', name: 'Double-leg calf raise', block: 'strength_support', phase: 'restore_motion',
    purpose: 'Rebuild calf/ankle strength for push-off.',
    why: 'Calf strength is a key contributor to ankle stability and push-off power.',
    equipment: ['bodyweight'], source_refs: ['ANKLE-CIT-002'],
    dosage_by_tier: [{ sets: '2-3', reps: '10-12' }, { sets: '3', reps: '15' }, { sets: '3', reps: '15-20' }],
    instructions: ['Rise onto the toes with both feet, lower slowly.'],
    regression: 'partial range / hold support', progression: 'AS-EX-022',
    cautions: [],
  },
  {
    id: 'AS-EX-013', name: 'Double-leg balance (firm surface, eyes open)', block: 'control_balance', phase: 'restore_motion',
    purpose: 'Begin re-establishing balance and proprioception.',
    why: 'Balance training reduces re-sprain risk and should start as early as tolerated (Schiftan 2015).',
    equipment: ['bodyweight'], source_refs: ['ANKLE-CIT-007'],
    dosage_by_tier: [{ sets: '3', hold: '20-30 s' }, { sets: '3', hold: '30-45 s' }, { sets: '4', hold: '45 s, eyes closed' }],
    instructions: ['Stand on both feet on a stable surface, focus on even weight distribution.'],
    regression: 'hold support', progression: 'AS-EX-023',
    cautions: [],
  },
  {
    id: 'AS-EX-014', name: 'Stationary cycling (light)', block: 'conditioning', phase: 'restore_motion',
    purpose: 'Maintain conditioning without impact.',
    why: 'Non-impact conditioning keeps fitness up while ligament healing continues.',
    equipment: ['bike'], source_refs: ['ANKLE-CIT-002'],
    dosage_by_tier: [{ sets: '—', detail: '5-10 min light' }, { sets: '—', detail: '10-15 min' }, { sets: '—', detail: '15-20 min' }],
    instructions: ['Keep resistance light and pain-free.'],
    regression: 'shorter duration', progression: 'add resistance',
    cautions: [],
  },

  // ═══ strength_balance: build capacity + proprioception ═══════════════════
  {
    id: 'AS-EX-020', name: 'Single-leg balance (firm -> unstable surface)', block: 'control_balance', phase: 'strength_balance',
    purpose: 'Progress balance/proprioception toward sport demands.',
    why: 'Single-leg balance progression is the core proprioceptive exercise shown to reduce re-sprain risk (Schiftan 2015).',
    equipment: ['bodyweight', 'balance_pad'], source_refs: ['ANKLE-CIT-007'],
    dosage_by_tier: [{ sets: '3', hold: '20-30 s' }, { sets: '3', hold: '30-45 s, add pad' }, { sets: '4', hold: '45 s, pad + head turns' }],
    instructions: ['Stand on the injured leg only, progress to an unstable surface as it gets easy.'],
    regression: 'AS-EX-013', progression: 'AS-EX-030',
    cautions: [],
  },
  {
    id: 'AS-EX-021', name: 'Resisted eversion / inversion strengthening', block: 'tissue_specific_loading', phase: 'strength_balance',
    purpose: 'Build peroneal (eversion) strength that dynamically protects against re-inversion.',
    why: 'Peroneal strength is a key dynamic stabiliser against future inversion sprains.',
    equipment: ['band'], source_refs: ['ANKLE-CIT-002', 'ANKLE-CIT-007'],
    dosage_by_tier: [{ sets: '3', reps: '12' }, { sets: '3', reps: '15' }, { sets: '4', reps: '15', load: 'stronger band' }],
    instructions: ['Push the foot outward (eversion) against band resistance, controlled return.'],
    regression: 'AS-EX-011', progression: 'AS-EX-031',
    cautions: [],
  },
  {
    id: 'AS-EX-022', name: 'Single-leg calf raise', block: 'strength_support', phase: 'strength_balance',
    purpose: 'Build single-leg push-off strength and symmetry.',
    why: 'Closing the single-leg calf strength gap is needed before running/jumping loads.',
    equipment: ['bodyweight'], source_refs: ['ANKLE-CIT-002'],
    dosage_by_tier: [{ sets: '2-3', reps: '8-10' }, { sets: '3', reps: '12' }, { sets: '3', reps: '15', load: 'add weight' }],
    instructions: ['Rise onto the toes on the injured leg only, lower slowly.'],
    regression: 'AS-EX-012', progression: 'AS-EX-032',
    cautions: [],
  },
  {
    id: 'AS-EX-023', name: 'Step-down / step-up control', block: 'strength_support', phase: 'strength_balance',
    purpose: 'Functional single-leg control in a familiar movement pattern.',
    why: 'Step control bridges isolated strength work to closed-chain function.',
    equipment: ['step'], source_refs: ['ANKLE-CIT-002'],
    dosage_by_tier: [{ sets: '2-3', reps: '8 each', height: 'low' }, { sets: '3', reps: '10 each' }, { sets: '3', reps: '12 each', height: 'higher' }],
    instructions: ['Step down/up slowly on the injured leg, control the landing.'],
    regression: 'lower step', progression: 'AS-EX-033',
    cautions: [],
  },
  {
    id: 'AS-EX-024', name: 'Double-leg to single-leg hop and stick', block: 'control_balance', phase: 'strength_balance',
    purpose: 'Introduce low-level landing control.',
    why: 'Landing control precedes reactive single-leg plyometrics.',
    equipment: ['bodyweight'], source_refs: ['ANKLE-CIT-007'],
    dosage_by_tier: [{ sets: '3', reps: '6' }, { sets: '3', reps: '8, single-leg landing' }, { sets: '4', reps: '8, single-leg' }],
    instructions: ['Hop forward and stick the landing softly, progressing to a single-leg landing.'],
    regression: 'smaller hop', progression: 'AS-EX-034',
    cautions: ['Land quietly and controlled — avoid rolling the ankle inward on landing.'],
  },
  {
    id: 'AS-EX-025', name: 'Jogging build-up (straight line)', block: 'running_sport_prep', phase: 'strength_balance',
    purpose: 'Reintroduce running load progressively.',
    why: 'Graded straight-line running precedes cutting and sprint work.',
    equipment: ['bodyweight'], source_refs: ['ANKLE-CIT-002'],
    dosage_by_tier: [{ sets: '—', detail: '60-70% effort, straight-line' }, { sets: '—', detail: '70-80% effort' }, { sets: '—', detail: '80% with strides' }],
    instructions: ['Build pace over the session, stay pain-free.'],
    regression: 'walk-jog intervals', progression: 'AS-EX-030',
    cautions: [],
  },

  // ═══ return_to_sport: agility, cutting, criteria-based return ════════════
  {
    id: 'AS-EX-030', name: 'Single-leg reactive balance (perturbation)', block: 'control_balance', phase: 'return_to_sport',
    purpose: 'High-level reactive balance to protect against sudden inversion moments.',
    why: 'Reactive/perturbation balance training targets the exact scenario that causes re-sprain.',
    equipment: ['bodyweight', 'balance_pad'], source_refs: ['ANKLE-CIT-007'],
    dosage_by_tier: [{ sets: '3', reps: '30 s reactive holds' }, { sets: '3', reps: '45 s with perturbation' }, { sets: '4', reps: '45 s with sport-specific distraction' }],
    instructions: ['Balance on the injured leg while reacting to unexpected small pushes or an unstable surface.'],
    regression: 'AS-EX-020', progression: 'maintain ongoing',
    cautions: [],
  },
  {
    id: 'AS-EX-031', name: 'Change-of-direction / cutting drills', block: 'running_sport_prep', phase: 'return_to_sport',
    purpose: 'Sport-specific cutting and deceleration exposure.',
    why: 'Cutting reproduces the load pattern most associated with re-injury — must be reintroduced gradually and confidently.',
    equipment: ['bodyweight', 'cones'], source_refs: ['ANKLE-CIT-002'],
    dosage_by_tier: [{ sets: '—', detail: 'planned wide-angle cuts' }, { sets: '—', detail: 'sharper / faster cuts' }, { sets: '—', detail: 'reactive cutting' }],
    instructions: ['Progress from planned, gentle direction changes to sharper and reactive cutting.'],
    regression: 'AS-EX-025', progression: 'AS-EX-032',
    cautions: [],
  },
  {
    id: 'AS-EX-032', name: 'Multidirectional plyometric progression', block: 'control_balance', phase: 'return_to_sport',
    purpose: 'Reactive strength and multidirectional landing control at sport-level demand.',
    why: 'Restores stretch-shortening capacity and directional control before full sport clearance.',
    equipment: ['bodyweight'], source_refs: ['ANKLE-CIT-007'],
    dosage_by_tier: [{ sets: '3', reps: '6 single-leg' }, { sets: '3', reps: '8 lateral bounds' }, { sets: '4', reps: '8 reactive multidirectional' }],
    instructions: ['Progress hops to bounds and lateral movement, focusing on soft, controlled landings.'],
    regression: 'AS-EX-024', progression: 'sport drills',
    cautions: [],
  },
  {
    id: 'AS-EX-033', name: 'Sport-specific skill loading', block: 'running_sport_prep', phase: 'return_to_sport',
    purpose: 'Integrate the ankle into sport-specific movements.',
    why: 'Skill-specific exposure precedes full training volume.',
    equipment: ['bodyweight'], source_refs: ['ANKLE-CIT-002'],
    dosage_by_tier: [{ sets: '—', detail: 'controlled skill reps' }, { sets: '—', detail: 'rising volume/intensity' }, { sets: '—', detail: 'near-match intensity' }],
    instructions: ['Build sport-specific skill volume toward match demands.'],
    regression: 'reduce intensity', progression: 'AS-EX-034',
    cautions: [],
  },
  {
    id: 'AS-EX-034', name: 'Return-to-sport criteria battery', block: 'control_balance', phase: 'return_to_sport',
    purpose: 'Objective gate before full return: strength + hop symmetry + confidence, brace/tape as needed.',
    why: 'Criteria-based return with ongoing balance training reduces re-sprain risk (Schiftan 2015; Vuurberg 2018).',
    equipment: ['bodyweight'], source_refs: ['ANKLE-CIT-002', 'ANKLE-CIT-007'], is_test: true,
    dosage_by_tier: [{ sets: '—', detail: 'single + triple + crossover hop LSI' }, { sets: '—', detail: 'calf strength LSI' }, { sets: '—', detail: 'all >=90% + pain-free + confident cutting' }],
    instructions: ['Compare injured vs uninjured on hop tests and calf-raise strength/endurance; target >=90% on all before full return.'],
    cautions: ['Consider ongoing bracing/taping for the first season back, especially if any test remains below 90%.'],
  },
];

/** Pool for a given stage. */
export function lateralSprainPool(stageId) {
  return LATERAL_SPRAIN_EXERCISES.filter((e) => e.phase === stageId);
}
